/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizar;

import carros.DAO;
import carros.Veiculos;
import javax.swing.JOptionPane;

/**
 *
 * @author Giova
 */
public class CadastroCarros extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCarros
     */
    Veiculos veiculos = new Veiculos();
    DAO dao;

    public CadastroCarros(DAO dao1) {
        this.dao = dao1;
        initComponents();

    }

    public CadastroCarros() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        lblNV1 = new javax.swing.JLabel();
        NomeVeiculo = new javax.swing.JTextField();
        jlbMV = new javax.swing.JLabel();
        MarcaVeiculo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AnoVeiculo = new javax.swing.JTextField();
        TipoVeiculo = new javax.swing.JComboBox<>();
        ValorVeiculo = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Carros");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastrar veículo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 3, 18))); // NOI18N
        jPanel1.setLayout(null);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setAlignmentX(0.3F);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar);
        btnCadastrar.setBounds(310, 280, 110, 40);

        lblNV1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblNV1.setText("Nome do veículo:");
        jPanel1.add(lblNV1);
        lblNV1.setBounds(40, 70, 130, 30);

        NomeVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(NomeVeiculo);
        NomeVeiculo.setBounds(170, 70, 230, 30);

        jlbMV.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jlbMV.setText("Marca do veículo:");
        jPanel1.add(jlbMV);
        jlbMV.setBounds(40, 110, 130, 30);
        jPanel1.add(MarcaVeiculo);
        MarcaVeiculo.setBounds(170, 110, 230, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Tipo do veículo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 150, 120, 40);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("Valor do veículo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 200, 120, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("Ano do veículo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 240, 120, 30);
        jPanel1.add(AnoVeiculo);
        AnoVeiculo.setBounds(170, 240, 230, 30);

        TipoVeiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Tipos de Veículos>", "SUV", "SEDAN", "PICAPE" }));
        jPanel1.add(TipoVeiculo);
        TipoVeiculo.setBounds(170, 150, 230, 40);
        jPanel1.add(ValorVeiculo);
        ValorVeiculo.setBounds(170, 200, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 480, 340);

        setBounds(0, 0, 535, 428);
    }// </editor-fold>//GEN-END:initComponents
     //ArrayList


    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        try {
            veiculos = new Veiculos();
            veiculos.setNomeVeiculo(NomeVeiculo.getText());
            veiculos.setTipoVeiculo(TipoVeiculo.getItemAt(WIDTH));
            veiculos.setMarcaVeiculo(MarcaVeiculo.getText());
            veiculos.setValorVeiculo(Double.parseDouble(ValorVeiculo.getText()));
            veiculos.setAnoVeiculo(Integer.parseInt(AnoVeiculo.getText()));
            dao.cadastrarVeiculo(veiculos);
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar veículo: " + e.getMessage());
        }


    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void NomeVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeVeiculoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCarros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoVeiculo;
    private javax.swing.JTextField MarcaVeiculo;
    private javax.swing.JTextField NomeVeiculo;
    private javax.swing.JComboBox<String> TipoVeiculo;
    private javax.swing.JFormattedTextField ValorVeiculo;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbMV;
    private javax.swing.JLabel lblNV1;
    // End of variables declaration//GEN-END:variables
}
