/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualizar;

import carros.DAO;
import carros.Veiculos;

/**
 *
 * @author Giova
 */
public class MostrarCcaro extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCarros
     */
    Veiculos veiculos = new Veiculos();
    DAO dao;

    public MostrarCcaro(DAO dao1) {
        this.dao = dao1;
        initComponents();

    }

    private MostrarCcaro() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnFiltrar = new javax.swing.JButton();
        AnoVeiculo = new javax.swing.JTextField();
        ValorVeiculo = new javax.swing.JTextField();
        TipoVeiculo = new javax.swing.JTextField();
        CodigoVeiculo = new javax.swing.JTextField();
        lblNV = new javax.swing.JLabel();
        jlbMV = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JMaiorvalor = new javax.swing.JRadioButton();
        JMenorvalor = new javax.swing.JRadioButton();
        lblNV1 = new javax.swing.JLabel();
        NomeVeiculo = new javax.swing.JTextField();
        MarcaVeiculo = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Carros");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Filtrar por valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 3, 18))); // NOI18N
        jPanel1.setLayout(null);

        btnFiltrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFiltrar);
        btnFiltrar.setBounds(430, 140, 80, 30);

        AnoVeiculo.setEditable(false);
        jPanel1.add(AnoVeiculo);
        AnoVeiculo.setBounds(170, 340, 230, 30);

        ValorVeiculo.setEditable(false);
        jPanel1.add(ValorVeiculo);
        ValorVeiculo.setBounds(170, 300, 230, 30);

        TipoVeiculo.setEditable(false);
        jPanel1.add(TipoVeiculo);
        TipoVeiculo.setBounds(170, 260, 230, 30);

        CodigoVeiculo.setEditable(false);
        CodigoVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(CodigoVeiculo);
        CodigoVeiculo.setBounds(170, 140, 230, 30);

        lblNV.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblNV.setText("Código do veículo:");
        jPanel1.add(lblNV);
        lblNV.setBounds(30, 140, 140, 30);

        jlbMV.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jlbMV.setText("Marca do veículo:");
        jPanel1.add(jlbMV);
        jlbMV.setBounds(40, 220, 130, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel1.setText("Tipo do veículo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 260, 120, 30);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel2.setText("Valor do veículo:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 300, 130, 30);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setText("Ano do veículo:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 340, 120, 30);

        buttonGroup1.add(JMaiorvalor);
        JMaiorvalor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JMaiorvalor.setText("Maior valor");
        jPanel1.add(JMaiorvalor);
        JMaiorvalor.setBounds(200, 70, 130, 29);

        buttonGroup1.add(JMenorvalor);
        JMenorvalor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JMenorvalor.setText("Menor valor");
        jPanel1.add(JMenorvalor);
        JMenorvalor.setBounds(40, 70, 120, 29);

        lblNV1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        lblNV1.setText("Nome do veículo:");
        jPanel1.add(lblNV1);
        lblNV1.setBounds(40, 180, 130, 30);

        NomeVeiculo.setEditable(false);
        NomeVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(NomeVeiculo);
        NomeVeiculo.setBounds(170, 180, 230, 30);

        MarcaVeiculo.setEditable(false);
        jPanel1.add(MarcaVeiculo);
        MarcaVeiculo.setBounds(170, 220, 230, 30);

        btnLimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpar);
        btnLimpar.setBounds(430, 180, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 530, 420);

        setBounds(0, 0, 581, 496);
    }// </editor-fold>//GEN-END:initComponents

    private void CodigoVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodigoVeiculoActionPerformed

    private void NomeVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeVeiculoActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
        if (JMaiorvalor.isSelected()) {
            veiculos = dao.mostrarMaiorValor("MAIOR");

        } else {
            veiculos = dao.mostrarMaiorValor("MENOR");
        }
        CodigoVeiculo.setText(String.valueOf(veiculos.getCodVeiculo()));
        NomeVeiculo.setText(veiculos.getNomeVeiculo());
        TipoVeiculo.setText(veiculos.getTipoVeiculo());
        MarcaVeiculo.setText(veiculos.getMarcaVeiculo());
        ValorVeiculo.setText(String.valueOf(veiculos.getValorVeiculo()));
        AnoVeiculo.setText(String.valueOf(veiculos.getAnoVeiculo()));
        
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        CodigoVeiculo.setText("");
        NomeVeiculo.setText("");
        TipoVeiculo.setText("");
        MarcaVeiculo.setText("");
        ValorVeiculo.setText("");
        AnoVeiculo.setText("");
        
    }//GEN-LAST:event_btnLimparActionPerformed
    //ArrayList

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarCcaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarCcaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarCcaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarCcaro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarCcaro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoVeiculo;
    private javax.swing.JTextField CodigoVeiculo;
    private javax.swing.JRadioButton JMaiorvalor;
    private javax.swing.JRadioButton JMenorvalor;
    private javax.swing.JTextField MarcaVeiculo;
    private javax.swing.JTextField NomeVeiculo;
    private javax.swing.JTextField TipoVeiculo;
    private javax.swing.JTextField ValorVeiculo;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbMV;
    private javax.swing.JLabel lblNV;
    private javax.swing.JLabel lblNV1;
    // End of variables declaration//GEN-END:variables
}
